#index:
#    path: /
#    controller: App\Controller\DefaultController::index


tesserakt_index:
    path: /
    controller: App\Controller\TesseraktController::index

tesserakt_cours:
    path: /cours
    controller: App\Controller\TesseraktCoursController::show

tesserakt_exercice:
    path: /exercice
    controller: App\Controller\TesseraktExerciceController::show