<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWWEMHbs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWWEMHbs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWWEMHbs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWWEMHbs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWWEMHbs\App_KernelDevDebugContainer([
    'container.build_hash' => 'WWEMHbs',
    'container.build_id' => 'f5f36d3c',
    'container.build_time' => 1589069592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWWEMHbs');
