<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2MoTyD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2MoTyD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2MoTyD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC2MoTyD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC2MoTyD\App_KernelDevDebugContainer([
    'container.build_hash' => 'C2MoTyD',
    'container.build_id' => 'a667d72a',
    'container.build_time' => 1589238666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2MoTyD');
